### ISSUE TITLE
Sublime Build 3148 white color is now gray.

### ISSUE THREAD

**Issue by alanaasmaa** [Monokai/monokai-pro-sublime-text#43]
Sublime Build 3148 white color is now gray. And it's hard to read it on dark background.

For an example PHP, HTML, JS Syntax

**Comment by alanaasmaa** [comment]
@Monokai Any updates ?

**Comment by Monokai** [comment]
I'm not seeing this. I just updated to 3149. There was a problem arising from update 3146, but that has been fixed already: https://github.com/Monokai/monokai-pro-sublime-text/issues/39#issuecomment-334914841

Do you let Package Control update your packages?

**Comment by alanaasmaa** [comment]
I have to check on Monday. I let Package Control to update but maybe update failed or something.

**Comment by alanaasmaa** [comment]
Yes, i reinstalled the package and now everything is good :) Thank you, didn't have had this kind of problem before.

**Comment by jdhartley** [comment]
To anyone else experiencing this issue, a full re-install of the Monokai Pro package is required to restore the white font.

Thanks!!

**Comment by giltig** [comment]
Hi, I have reinstalled sublime and the package and I'm still having this issue on sublime build 3156
Please help
<img width="1920" alt="screen shot 2017-12-11 at 11 08 46 am" src="https://user-images.githubusercontent.com/5754742/33823429-cf38b47c-de63-11e7-91f8-7cc41d69d27c.png">
